vnet_name                = "vnet1_dataplatform_poa"
vnet_resource_group_name = "rg_dataplatform_poa"
snet_name                = "test_pep_sub3"
storage_account_name     = "dataplatformtfbackend"
resource_group_name      = "rg_dataplatform_tf"
location                 = "West Europe"
project                  = "idf"
